import 'package:sea_night_be_brave/models/models.dart';
import 'package:sea_night_be_brave/utils/utils.dart';

final List<Level> levels = [
  const Level(
    id: 0,
    level: 'Normal',
    asset: 'assets/png/mike.png',
    description: 'A large number of finds and a small number of obstacles',
    golds: 12,
    emeralds: 6,
    diamonds: 3,
    luckyCoin: 3,
    unluckyCoin: 3,
    worms: 3,
    sharks: 3,
    width: 308,
    height: 543,
    color: AppTheme.green,
  ),
  const Level(
    id: 1,
    level: 'Hard',
    asset: 'assets/png/david.png',
    description: 'Moderate number of finds and more obstacles',
    golds: 10,
    emeralds: 5,
    diamonds: 3,
    luckyCoin: 3,
    unluckyCoin: 4,
    worms: 4,
    sharks: 4,
    width: 377,
    height: 526,
    color: AppTheme.yellow,
  ),
  const Level(
    id: 2,
    level: 'Extreme',
    asset: 'assets/png/david.png',
    description: 'Moderate number of finds and more obstacles',
    golds: 8,
    emeralds: 4,
    diamonds: 2,
    luckyCoin: 2,
    unluckyCoin: 5,
    worms: 5,
    sharks: 5,
    width: 390,
    height: 535,
    color: AppTheme.red,
  ),
];
